export const MUTATION_SET = 'setItem'
export const MUTATION_ADD = 'addItem'
export const MUTATION_REMOVE = 'removeItem'
export const MUTATION_TOTAL = 'total'
export const MUTATION_PAGENUMBER = 'changePage'
